// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokestopHotSpots.Data;

#nullable disable

namespace PokestopHotSpots.Migrations
{
    [DbContext(typeof(PokestopHotspotContext))]
    [Migration("20261001195754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokestopHotSpots.Models.Hotspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PokestopDensity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasParking")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Hotspots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GymCount = 6,
                            Name = "Lakefront Park",
                            PokestopDensity = "High",
                            hasParking = true
                        },
                        new
                        {
                            Id = 2,
                            GymCount = 4,
                            Name = "Veterans Park",
                            PokestopDensity = "High",
                            hasParking = true
                        },
                        new
                        {
                            Id = 3,
                            GymCount = 3,
                            Name = "Milwaukee Public Market",
                            PokestopDensity = "High",
                            hasParking = false
                        },
                        new
                        {
                            Id = 4,
                            GymCount = 4,
                            Name = "Historic Third Ward",
                            PokestopDensity = "High",
                            hasParking = false
                        },
                        new
                        {
                            Id = 5,
                            GymCount = 3,
                            Name = "Bradford Beach",
                            PokestopDensity = "Medium",
                            hasParking = true
                        },
                        new
                        {
                            Id = 6,
                            GymCount = 4,
                            Name = "Washington Park",
                            PokestopDensity = "Medium",
                            hasParking = true
                        },
                        new
                        {
                            Id = 7,
                            GymCount = 3,
                            Name = "Mitchell Park Domes",
                            PokestopDensity = "Medium",
                            hasParking = true
                        },
                        new
                        {
                            Id = 8,
                            GymCount = 2,
                            Name = "Humboldt Park",
                            PokestopDensity = "Medium",
                            hasParking = true
                        },
                        new
                        {
                            Id = 9,
                            GymCount = 2,
                            Name = "Bay View Park",
                            PokestopDensity = "Low",
                            hasParking = true
                        },
                        new
                        {
                            Id = 10,
                            GymCount = 2,
                            Name = "Kletzsch Park",
                            PokestopDensity = "Low",
                            hasParking = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
